/**
 * ProjectMetadata.gs — truthful release metadata for the stabilized bundle.
 */

const PROJECT_RELEASE_NAMING_ = Object.freeze({
  stage: '7.2',
  stageLabel: 'Stage 7.2 — Stabilized SEND_PANEL Baseline',
  stageVersion: '7.2.0',
  activeBaseline: 'stage7-2-stabilized-send-panel-baseline'
});

const PROJECT_BUNDLE_METADATA_ = Object.freeze({
  stage: PROJECT_RELEASE_NAMING_.stage,
  stageLabel: PROJECT_RELEASE_NAMING_.stageLabel,
  stageVersion: PROJECT_RELEASE_NAMING_.stageVersion,
  release: PROJECT_RELEASE_NAMING_,
  packagingPolicy: 'root-files-only',
  notes: [
    'README.md and ProjectMetadata.gs were rewritten to match the actual archive contents.',
    'The release zip must not include .git or node_modules.',
    'Only .clasp.json.example belongs in the repository.'
  ]
});

const PROJECT_BUNDLE_FILE_INDEX_ = Object.freeze([
  ".clasp.json.example",
  ".claspignore",
  ".gitignore",
  "ARCHITECTURE.md",
  "Actions.gs",
  "AuditTrail.gs",
  "COMMANDS_TERMINAL.md",
  "Code.gs",
  "DataAccess.gs",
  "DateUtils.gs",
  "DeprecatedRegistry.gs",
  "Diagnostics.gs",
  "DialogPresenter.gs",
  "DialogTemplates.gs",
  "Dialogs.gs",
  "DictionaryRepository.gs",
  "DomainTests.gs",
  "HtmlUtils.gs",
  "JavaScript.html",
  "JobRuntime.gs",
  "JobRuntimeRepository.gs",
  "Js.Actions.html",
  "Js.Api.html",
  "Js.Core.html",
  "Js.Diagnostics.html",
  "Js.Events.html",
  "Js.Helpers.html",
  "Js.Render.html",
  "Js.State.html",
  "Log.gs",
  "LogsRepository.gs",
  "MonthSheets.gs",
  "OperationRepository.gs",
  "OperationSafety.gs",
  "PersonCalendar.html",
  "PersonCards.gs",
  "PersonsRepository.gs",
  "PreviewLinkService.gs",
  "ProjectMetadata.gs",
  "README.md",
  "Reconciliation.gs",
  "RoutingRegistry.gs",
  "STABILIZATION_NOTES_2026-03-22.md",
  "STAGE7_REPORT.md",
  "SelectionActionService.gs",
  "SendPanel.gs",
  "SendPanelConstants.gs",
  "SendPanelRepository.gs",
  "SendPanelService.gs",
  "ServerResponse.gs",
  "SheetSchemas.gs",
  "SheetStandards.gs",
  "Sidebar.html",
  "SidebarServer.gs",
  "SmokeTests.gs",
  "SpreadsheetActionsApi.gs",
  "Stage3ServerApi.gs",
  "Stage4Config.gs",
  "Stage4MaintenanceApi.gs",
  "Stage4ServerApi.gs",
  "Stage5MaintenanceApi.gs",
  "Styles.html",
  "Summaries.gs",
  "SummaryRepository.gs",
  "SummaryService.gs",
  "TemplateRegistry.gs",
  "TemplateResolver.gs",
  "Templates.gs",
  "Triggers.gs",
  "UseCases.gs",
  "Utils.gs",
  "VacationEngine.gs",
  "VacationService.gs",
  "VacationsRepository.gs",
  "Validation.gs",
  "WorkflowOrchestrator.gs",
  "appsscript.json",
  "dev-shell.ps1",
  "package.json",
  "watch-sync-simple.ps1"
]);
